Repository dhsong215/pacman, pull requests merged in 2024-05, with the labels that each got.

#18 쿠키, 파워쿠키, 교차로 노드 추가
  Assets/Art/New Folder.meta
  Assets/Prefabs/Node.prefab
  Assets/Prefabs/Node.prefab.meta
  Assets/Prefabs/Pallet.prefab
  Assets/Prefabs/Pallet.prefab.meta
  Assets/Prefabs/PowerPallet.prefab
  Assets/Prefabs/PowerPallet.prefab.meta
  Assets/Scenes/GameScene.unity
  Assets/Sprites/TilePalette.prefab
  Assets/wall/Node_tile.asset
  Assets/wall/Node_tile.asset.meta
  Assets/wall/Pellet_tile.asset
  Assets/wall/Pellet_tile.asset.meta
  Assets/wall/PowerPellet_tile.asset
  Assets/wall/PowerPellet_tile.asset.meta
Labels: enhancement

#20 [DOCS] Update README.md
  README.md
Labels: documentation

#19 AroundWrap 스크립트 작성
  Assets/Scripts/AroundWrap.cs
  Assets/Scripts/AroundWrap.cs.meta
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GameManager.cs.meta
  Assets/Scripts/Pellet.cs
  Assets/Scripts/Pellet.cs.meta
  Assets/Scripts/PowerPellet.cs
  Assets/Scripts/PowerPellet.cs.meta
  Assets/Scripts/StageData.cs
  Assets/Scripts/StageData.cs.meta
Labels: enhancement

#27 scatter 모드 추가
  Assets/Scripts/GhostScatter.cs
  Assets/Scripts/Movement.cs
  Assets/Scripts/Node.cs
  Assets/Scripts/Node.cs.meta
Labels: enhancement

#32 [Feature] Ghost Chase 모드 추가
  Assets/Scripts/GhostChase.cs
Labels: enhancement

#37 Feature/Ghost Home모드 추가
  Assets/Scenes/GameScene.unity
  Assets/Scripts/Ghost.cs
  Assets/Scripts/GhostHome.cs
  Assets/Sprites/Ghost_blue 1_0.controller
  Assets/Sprites/Ghost_blue 1_0.controller.meta
  Assets/Sprites/Ghost_blue.anim
  Assets/Sprites/Ghost_blue.anim.meta
Labels: enhancement

#40 Feature/ghost frightened모드 추가
  Assets/Scripts/GhostFrightened.cs
Labels: enhancement

#41 Bug/GameManager신텍스 에러 수정
  Assets/Scripts/GameManager.cs
  Assets/Scripts/GameManager.cs.meta
Labels: bug

#51 BUG/fix error
  Assets/Scenes/GameScene.unity
  Assets/Scripts/GameManager.cs
Labels: bug
